version: '3.8'
services:
  flask-backend:
    container_name: "flask-backend"
    build:
      context: .
      dockerfile: Dockerfile
    image: "flask-backend"
    ports:
      - "5060:5060"
    stdin_open: true
    restart: always
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql
    restart: always
    container_name: db_service
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_DATABASE=flask_assignment_db"
      - "MYSQL_USER=root_1"
      - "MYSQL_PASSWORD=root_1"
      - "MYSQL_ROOT_PASSWORD=root_1"
    volumes:
      - ./database_schema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
volumes:
  db:
    driver: local
